# Generated by Django 4.2.2 on 2023-06-27 16:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='phonecode',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
