# Generated by Django 4.2.2 on 2023-06-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customertype',
            field=models.CharField(choices=[(1, 'person'), (2, 'company')], default=1, max_length=20),
        ),
    ]
