# Generated by Django 4.2.2 on 2023-06-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0006_alter_customer_customertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customertype',
            field=models.IntegerField(choices=[(1, 'person'), (2, 'company')], default=0),
        ),
    ]
