# Generated by Django 4.2.2 on 2023-06-28 09:46

from django.db import migrations, models
import django.db.models.deletion
import phonebook.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0008_alter_customer_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postalcode',
            field=models.CharField(blank=True, max_length=10, validators=[phonebook.models.numeric_charfield_validator]),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('mobilenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('faxnumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='phonebook.customer')),
            ],
        ),
    ]
