# Generated by Django 4.2.2 on 2023-06-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0009_alter_customer_address_alter_customer_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='phonecode',
        ),
    ]
